// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Registration.Infrastructure.Database;

#nullable disable

namespace Registration.Infrastructure.Database.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    partial class RegistrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registration")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Registration.Domain.Entities.Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_participant_id");

                    b.HasKey("Id")
                        .HasName("pk_codes");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_codes_token");

                    b.HasIndex("UsedByParticipantId")
                        .HasDatabaseName("ix_codes_used_by_participant_id");

                    b.ToTable("codes", "registration");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            EventId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsUsed = false,
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Token = "BECA-UCB-100"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            EventId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsUsed = true,
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Token = "DESC-50-VIP",
                            UsedAt = new DateTime(2026, 5, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            UsedByParticipantId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", "registration");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ContactEmail = "usuarioprueba40@gmail.com",
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("99999999-9999-9999-9999-999999999999"),
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("QrIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_identifier");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_participants_order_id");

                    b.HasIndex("QrIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_participants_qr_identifier");

                    b.ToTable("participants", "registration");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            FullName = "Jonathan Rocha",
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Phone = "77712345",
                            QrIdentifier = "HASH_QR_SEGURO_001"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Code", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Participant", "UsedByParticipant")
                        .WithMany()
                        .HasForeignKey("UsedByParticipantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_codes_participants_used_by_participant_id");

                    b.Navigation("UsedByParticipant");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Participant", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Order", "Order")
                        .WithMany("Participants")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Order", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
