services:
  campeando-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=${JWT_EXPIRY_MINUTES}

    build:
      target: final

    ports:
      - "${BACKEND_PORT}:8080"

  campeando-frontend:
    build:
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL}

    ports:
      - "${FRONTEND_PORT}:80"