services:
  campeando-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
    build:
      target: development

    ports:
      - "${BACKEND_PORT:-5206}:5206"
      
    volumes:
      - ./backend:/app

  campeando-frontend:
    build:
      target: development

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
    - VITE_API_URL=${VITE_API_URL:-http://localhost:5206/api}

    ports:
      - "${FRONTEND_PORT:-5173}:5173"

  # campeando-database:
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  #   ports:
  #     - "${POSTGRES_PORT:-5432}:5432"