services:
  campeando-backend:
    image: campeando-backend:${TAG:-latest}
    build:
      context: ./backend

  campeando-frontend:
    image: campeando-frontend:${TAG:-latest}
    build:
      context: ./frontend