  database-configuration[m
  events-view-and-creation[m
  feat/CR-events[m
  feat/logistic-module-config[m
  feat/md-registration-conf[m
  feat/module-registration-config[m
  feat/payment-module-configuration[m
  first-presentation-fixes[m
  loading-skeletons[m
* [32mmain[m
  mutations[m
  tenant-mock-creation[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/auth-frontend[m
  [31mremotes/origin/auth-w-tests[m
  [31mremotes/origin/database-configuration[m
  [31mremotes/origin/event-inscription[m
  [31mremotes/origin/events-view-and-creation[m
  [31mremotes/origin/exercise-docker/rafael-vargas[m
  [31mremotes/origin/fake-auth[m
  [31mremotes/origin/feat/CR-events[m
  [31mremotes/origin/feat/logistic-module-config[m
  [31mremotes/origin/feat/md-registration-conf[m
  [31mremotes/origin/feat/module-registration-config[m
  [31mremotes/origin/feat/payment-module-configuration[m
  [31mremotes/origin/first-presentation-fixes[m
  [31mremotes/origin/infrastructure-final-conf[m
  [31mremotes/origin/loading-skeletons[m
  [31mremotes/origin/main[m
  [31mremotes/origin/mock-api-connection[m
  [31mremotes/origin/mutations[m
  [31mremotes/origin/refactor-frontend[m
  [31mremotes/origin/tanstack-query[m
  [31mremotes/origin/tenant-mock-creation[m
