<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Web.API</RootNamespace>
      <UserSecretsId>1f9fc073-e995-4eb7-b582-4a5f81f2bb7d</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Modules\Core\Core.Infrastructure\Core.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Core\Core.Presentation\Core.Presentation.csproj" />
      <ProjectReference Include="..\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Identity\Identity.Presentation\Identity.Presentation.csproj" />
      <ProjectReference Include="..\Modules\Logistics\Logistics.Infrastructure\Logistics.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Payment\Payment.Infrastructure\Payment.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Registration\Registration.Infrastructure\Registration.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Registration\Registration.Presentation\Registration.Presentation.csproj" />
    </ItemGroup>

</Project>
