<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Web.API</RootNamespace>
      <UserSecretsId>5605e01e-35f2-4722-b1a4-6ead8130093c</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Modules\Events\Events.Presentation\Events.Presentation.csproj" />
      <ProjectReference Include="..\Modules\Events\Events.Infrastructure\Events.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
      <ProjectReference Include="..\Modules\Identity\Identity.Presentation\Identity.Presentation.csproj" />
    </ItemGroup>

</Project>
