// <auto-generated />
using System;
using Logistics.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Infrastructure.Database.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    partial class LogisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logistics")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistics.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("OfflineSyncId")
                        .HasColumnType("text")
                        .HasColumnName("offline_sync_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<Guid?>("RationConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("ration_config_id");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.HasKey("Id")
                        .HasName("pk_check_ins");

                    b.HasIndex("OfflineSyncId")
                        .IsUnique()
                        .HasDatabaseName("ix_check_ins_offline_sync_id");

                    b.HasIndex("RationConfigId")
                        .HasDatabaseName("ix_check_ins_ration_config_id");

                    b.ToTable("check_ins", "logistics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            EventId = new Guid("99999999-9999-9999-9999-999999999999"),
                            OfflineSyncId = "sync_001_mobile",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParticipantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ScannedAt = new DateTime(2026, 5, 20, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Logistics.Domain.Entities.OfflineSyncProjection", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("QrIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qr_identifier");

                    b.HasKey("ParticipantId")
                        .HasName("pk_offline_sync_projections");

                    b.ToTable("offline_sync_projections", "logistics");

                    b.HasData(
                        new
                        {
                            ParticipantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            EventId = new Guid("99999999-9999-9999-9999-999999999999"),
                            FullName = "Jonathan Rocha",
                            IsConfirmed = true,
                            LastUpdatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            QrIdentifier = "HASH_QR_SEGURO_001"
                        });
                });

            modelBuilder.Entity("Logistics.Domain.Entities.RationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("TotalAllowedPerParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("total_allowed_per_participant");

                    b.HasKey("Id")
                        .HasName("pk_ration_configs");

                    b.ToTable("ration_configs", "logistics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            EventId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Almuerzo Día 1",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TotalAllowedPerParticipant = 1
                        });
                });

            modelBuilder.Entity("Logistics.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("Logistics.Domain.Entities.RationConfig", "RationConfig")
                        .WithMany("CheckIns")
                        .HasForeignKey("RationConfigId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_check_ins_ration_configs_ration_config_id");

                    b.Navigation("RationConfig");
                });

            modelBuilder.Entity("Logistics.Domain.Entities.RationConfig", b =>
                {
                    b.Navigation("CheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
