// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payment.Infrastructure.Database;

#nullable disable

namespace Payment.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payment.Domain.Entities.ManualReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_manual_receipts");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasDatabaseName("ix_manual_receipts_file_hash");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_manual_receipts_transaction_id");

                    b.ToTable("manual_receipts", "payment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            FileHash = "HASH_IMAGEN_SHA256_ABC123",
                            FileUrl = "https://s3.amazonaws.com/tu-bucket/comprobante_001.jpg",
                            MimeType = "image/jpeg",
                            TransactionId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UploadedAt = new DateTime(2026, 5, 20, 1, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Payment.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_order_id");

                    b.ToTable("transactions", "payment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Amount = 150.00m,
                            CreatedAt = new DateTime(2026, 5, 20, 1, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Verified"
                        });
                });

            modelBuilder.Entity("Payment.Domain.Entities.ManualReceipt", b =>
                {
                    b.HasOne("Payment.Domain.Entities.Transaction", "Transaction")
                        .WithMany("ManualReceipts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_manual_receipts_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Payment.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("ManualReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
