name: CI Frontend

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'frontend/**'

jobs:
  ci-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Paso 2: Código Limpio (Lint/Format)
        run: pnpm biome ci .
        working-directory: frontend

      - name: Paso 3: Build Check
        run: pnpm build
        working-directory: frontend
        env:
          VITE_API_URL: http://localhost:5000/api

      - name: Paso 4: Docker Build Check
        run: docker build ./frontend -t frontend-app:test
